### PR TITLE
Add transformer

### PR DESCRIPTION
**Pull request by luisvt**
- add constrouctor ParserGeneratorOptions.fromMap so we can pass map options provenient from transformer
- add PegTransformer that listen on any change of any dart file and produce parser file automatically (We should change this to listen on peg files changes instead)
- add abstract_parser.dart which contains two classes AbstractParser and AbstractParserError. Those classes colud be extended by user to have autocompletion in the receiver code.

### CODE REVIEW

**Comment by mezoni** [comment]
Need time for rethinking.

**Comment by luisvt** [comment]
Please view sample code at https://github.com/luisvt/peg_transformer_sample and also review changes to readme. I think we don't need to put the entire generated code and stats

**Comment by luisvt** [comment]
I have also added sample web code if you are interested

**Comment by luisvt** [comment]
by the way, now transformer listen on peg files changes instead of dart files.

**Comment by mezoni** [comment]
Thank you.
Your suggestions requires time for innovations that are not originally planned.
Currently I only have free time to correct found bugs.

**Pull request closed without merging**
